import 'package:flutter/material.dart';
import 'barrios_santa_marta.dart';


const List<String> barriosSantaMarta = [
  "1º de Mayo",
  "Acacias",
  "Boulevard de la 19",
  "Calle 29 hasta la Cra. 5ª",
  "Cañaveral",
  "Ciudadela 29 de Julio",
  "Corea",
  "Daniel Sánchez",
  "El Piñon I",
  "El Piñon II",
  "El Trébol",
  "La Lucha",
  "Las Américas",
  "Las Colinas del Pando",
  "Loma Fresca",
  "Los Faroles",
  "Los Laureles",
  "Loteo Graciela Riascos",
  "Manzanares",
  "María Eugenia",
  "Martinete",
  "Murallas",
  "Pando",
  "Pando I",
  "Pastrana",
  "Privilegio",
  "San José Del S",
  "San Pablo",
  "Urbanización Villas de Alejandría",
  "Veinte de Enero",
  "Villa del Carmen",
  "Villa del Mar",
  "Villa Marbella",
  "20 de Octubre",
  "Av. Libertador - P. Mamatoco",
  "Bolivariana",
  "Conjunto Residencial Canarias",
  "Cantilito I",
  "Cantilito II",
  "Cantilito III",
  "Cantilito IV",
  "El Bosque",
  "El Carmen",
  "El Cisne",
  "El Refugio",
  "Invasión Nueva La Rosalía",
  "Los Trupillos",
  "Las Malvinas",
  "Mamatoco",
  "Nueva Colombia",
  "Nueva Mansión",
  "Nueva Venecia",
  "Nuevo Milenio",
  "Once de Noviembre",
  "Quebrada M.",
  "Rodrigo Ahumada",
  "San Tropel",
  "Timayui I",
  "Timayui II",
  "Timayui III",
  "Tres Puentes",
  "Urbanización Alejandrina",
  "Urbanización Boulevard del Rio",
  "Urbanización Garagoa",
  "Urbanización Villa del Mar",
  "Villa Campo",
  "Villa Dania",
  "Villa Ely",
  "Villa Italia",
  "Villa Marina",
  "Villa Mercedes",
  "Villa Sara",
  "Villa Toledo",
  "Villa Trinidad",
  "Villa U",
  "Yucal 1",
  "Yucal 2",
  "Acodis",
  "Altos Santa Cruz",
  "Andrea Carolina",
  "Asocom Corintio",
  "Curinca",
  "La Concepción II",
  "La Concepción III",
  "La Concepción IV",
  "La Concepción V",
  "La Lucha - 19 de Abril",
  "Líbano 2000",
  "Los Nogales",
  "Los Pinos",
  "Luz del Mundo",
  "Montpellier",
  "Santa Clara",
  "Alto de Santa Cruz",
  "Santa Cruz",
  "Santa Lucía",
  "Tamacá",
  "Tejares del Libertador",
  "Urbanización El Parque",
  "Urbanización Mayorga",
  "Villas de Santa Cruz",
  "Philadelfia",
  "Brisas de La Sierra",
  "Zona Franca Industrial",
  "Ciudad del Sol",
  "Alambique",
  "Bavaria",
  "Bavaria Reservado",
  "Bellavista",
  "Bolívar",
  "Boston",
  "Centro",
  "Centro Histórico",
  "Costa Verde",
  "El Mayor",
  "El Prado",
  "El Pueblito",
  "El Territorial",
  "Urbanización Colón",
  "La Esperanza",
  "La Gran Vía",
  "La Logia",
  "La Tenería",
  "Los Ángeles",
  "Los Troncos",
  "Minuto de Dios",
  "Miramar",
  "Obrero",
  "Puerto Mosquito",
  "Santa Cecilia",
  "Santa Veronica",
  "Taminaca 1",
  "Taminaca 2",
  "Tierra Baja",
  "Trece de Junio",
  "Urbanización El Refugio",
  "Villa del Rosario",
  "Zona del Mercado",
  "Alfonso López",
  "Almendro",
  "Betania",
  "César Mendoza",
  "20 de Julio",
  "Barrio Obrero",
  "Cristo Rey",
  "Nacho Vives",
  "El Pradito",
  "El Recreo",
  "Ensenada Juan XXIII 1",
  "Ensenada Juan XXIII 2",
  "Ensenada",
  "Olaya",
  "Los Almendros",
  "Manguitos",
  "Miraflores",
  "Olaya Herrera",
  "Pescaito",
  "San Fernando",
  "San Jorge",
  "San Martín",
  "Urbanización Berlín",
  "Urbanización Campo Alegre",
  "Urbanización Guido",
  "Urbanización Hábitat",
  "Urbanización Pérez Dávila",
  "Urbanización Riascos",
  "Urbanización Veracruz",
  "Veracruz",
  "13 de Junio",
  "Altos de Santa Rita",
  "El Olivo",
  "7 de Agosto",
  "Los Alcázares",
  "Alto Jardín",
  "Andrea Doria",
  "AV. Del Río III Etapa",
  "Boston Caribe Inn",
  "El Cundí",
  "Elvira María",
  "Jardín",
  "Libertador",
  "Los Cocos",
  "Mercado Público",
  "Modelo",
  "Municipal",
  "Nueva Granada",
  "Urbanización Las Delicias",
  "Nuevo Jardín",
  "Pepe Hurtado",
  "Perehuétano",
  "Porvenir",
  "Postobón",
  "Recreo",
  "Salamanca",
  "San Francisco",
  "San José",
  "Santa Catalina",
  "Santa Catalina 2000",
  "Santa Helena",
  "Urb. Benjamín Alzate",
  "Urbanización Autopista",
  "Urbanización Bavaria Country",
  "Urbanización Caracas",
  "Urbanización El Río",
  "Urbanización Elvia Mejía",
  "Urbanización Guerrero",
  "Urbanización Los Cerros",
  "Urbanización Nuevo Jardín",
  "Urbanización Pradera",
  "Urbanización Reposo",
  "Urbanización San Carlos",
  "Urbanización Santa Elena",
  "Urbanización Santa Rita",
  "Urbanización Silvia Rosa",
  "17 de Diciembre",
  "8 de Diciembre",
  "8 de Febrero",
  "8 de Noviembre",
  "Altos Delicias",
  "Altos Simón Bolívar",
  "Altos Villa Concha",
  "Balcones del Libertador",
  "Bastidas",
  "Belén",
  "Benjamín Alzate",
  "Buenos Aires",
  "Cardonales",
  "Chimila 1",
  "Chimila 2",
  "Divino Niño",
  "El Pantano",
  "Esmeralda",
  "Florida",
  "Galán",
  "Galicia",
  "La Estrella",
  "La Unión",
  "Las Vegas",
  "Los Fundadores",
  "Luis R. Calvo",
  "Miguel Pinedo",
  "Nueva Galicia",
  "Nuevo Armero",
  "Oasis",
  "Ondas del Caribe",
  "Pamplonita",
  "Paraíso",
  "San Ramón",
  "Santa Mónica",
  "Santafé",
  "Simón Bolívar",
  "Tayrona 1",
  "Tayrona 2",
  "Urbanización Santa Lucía",
  "Villa Aurora",
  "Villa Betel",
  "Villa del Carmen",
  "Villa del Río",
  "Brisas del Lago",
  "Cerro Intermedio",
  "Cerro La Llorona",
  "Cerro La Virgen",
  "Cerro M Cristal",
  "Doce de Octubre",
  "Eduardo Gutiérrez",
  "El Carmen",
  "El Socorro",
  "El Valle de Gaira",
  "Gaira Centro",
  "La Magdalena",
  "La Quemada",
  "La Quinina",
  "Lago Dulcino",
  "Las Colinas",
  "Las Palmeras",
  "Nueva Betel",
  "Rodadero Tradicional",
  "Sarabanda",
  "Vereda Mosquito",
  "Villa Berlín",
  "Villa Tanga",
  "Puente Arhuacos",
  "Bella Vista",
  "Bello",
  "Sol Cristalina",
  "Cristo Rey",
  "Don Jaca",
  "Alto El Mango",
  "Gauchovand",
  "La Chivera",
  "La Eva",
  "La Paz",
  "Limón",
  "Los Lirios",
  "Sircasia",
  "Totumo",
  "Villa Taroa",
  "Vista del Mar",
  "Vista Hermosa",
  "Bonda",
  "Bello horizonte",
  "La Concepción I"
];


class BarrioSearchField extends StatefulWidget {
  final TextEditingController controller;

  const BarrioSearchField({super.key, required this.controller});

  @override
  State<BarrioSearchField> createState() => _BarrioSearchFieldState();
}

class _BarrioSearchFieldState extends State<BarrioSearchField> {
  List<String> filtered = [];
  bool showList = false;

  @override
  void initState() {
    super.initState();
    filtered = barriosSantaMarta;
  }

  void updateSearch(String query) {
    setState(() {
      filtered = barriosSantaMarta
          .where((b) => b.toLowerCase().contains(query.toLowerCase()))
          .toList();
      showList = query.isNotEmpty;
    });
  }

  @override
  Widget build(BuildContext context) {
    // compute dynamic height for the results list (item height ~56)
    final double maxListHeight = 240.0;
    const double itemHeight = 56.0;
    double listHeight = (filtered.length * itemHeight);
    if (listHeight < itemHeight) listHeight = itemHeight;
    if (listHeight > maxListHeight) listHeight = maxListHeight;

    return Column(
      children: [
        TextField(
          controller: widget.controller,
          onChanged: updateSearch,
          decoration: InputDecoration(
            labelText: "Barrio",
            hintText: "Escribe el barrio...",
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            prefixIcon: const Icon(Icons.search),
          ),
        ),

        // Lista desplegable de resultados (height adjusts to content, up to max)
        if (showList)
          Container(
            margin: const EdgeInsets.only(top: 5),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.grey.shade300),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.05),
                  blurRadius: 4,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            child: SizedBox(
              height: listHeight,
              child: ListView.builder(
                padding: EdgeInsets.zero,
                itemCount: filtered.length,
                itemBuilder: (context, index) {
                  final barrio = filtered[index];
                  return ListTile(
                    title: Text(barrio),
                    onTap: () {
                      widget.controller.text = barrio;
                      setState(() => showList = false);
                    },
                  );
                },
              ),
            ),
          ),
      ],
    );
  }
}



