// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIbn5JPVKgaP4yXN9prI_9ii7gUwHHA0',
    appId: '1:427371804806:web:04e2e192df1b31d0f8b907',
    messagingSenderId: '427371804806',
    projectId: 'safemap-b7dce',
    authDomain: 'safemap-b7dce.firebaseapp.com',
    storageBucket: 'safemap-b7dce.firebasestorage.app',
    measurementId: 'G-G42CD2VHT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyCunxPyuOz9CiFVJFXzqEmZxabSkN3ek',
    appId: '1:427371804806:android:48cc2e3447ec13e9f8b907',
    messagingSenderId: '427371804806',
    projectId: 'safemap-b7dce',
    storageBucket: 'safemap-b7dce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaN219fLv6uGZlC1_EPXIAr28qxUV6BsU',
    appId: '1:427371804806:ios:6a3c589b05790467f8b907',
    messagingSenderId: '427371804806',
    projectId: 'safemap-b7dce',
    storageBucket: 'safemap-b7dce.firebasestorage.app',
    iosBundleId: 'com.example.safeMapApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaN219fLv6uGZlC1_EPXIAr28qxUV6BsU',
    appId: '1:427371804806:ios:6a3c589b05790467f8b907',
    messagingSenderId: '427371804806',
    projectId: 'safemap-b7dce',
    storageBucket: 'safemap-b7dce.firebasestorage.app',
    iosBundleId: 'com.example.safeMapApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChIbn5JPVKgaP4yXN9prI_9ii7gUwHHA0',
    appId: '1:427371804806:web:36be66960abd8f3bf8b907',
    messagingSenderId: '427371804806',
    projectId: 'safemap-b7dce',
    authDomain: 'safemap-b7dce.firebaseapp.com',
    storageBucket: 'safemap-b7dce.firebasestorage.app',
    measurementId: 'G-LX2QZT94MN',
  );
}
